name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:   #job name
    runs-on: ubuntu-latest

    permissions:
      id-token: write   #generate OIDC token
      contents: read    #to read the repo and get the workflow file

    env:
      AWS_REGION: ap-south-1
      AWS_ACCOUNT_ID: 165772574272
      ECR_URI: 165772574272.dkr.ecr.ap-south-1.amazonaws.com/database-dump-backend
      ECS_CLUSTER: database-dump-cluster
      ECS_SERVICE: database-dump-backend-service
      ECS_TASK_DEFINITION: database-dump-backend

    steps:
      - uses: actions/checkout@v4   #checkout the code from the repository to the runner

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4  #pre-built action to configure AWS credentials using OIDC
        with:   #parameters for the AWS credentials action
          role-to-assume: arn:aws:iam::165772574272:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |  #shell command to login to AWS ECR using temporary credentials obtained from the OIDC token
          aws ecr get-login-password \
          | docker login --username AWS --password-stdin $ECR_URI
      
      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build --no-cache \
            -t app:${{ github.sha }} .

      - name: Tag image
        run: docker tag \
          app:${{ github.sha }} \
          $ECR_URI:${{ github.sha }}

      - name: Push image
        run: docker push $ECR_URI:${{ github.sha }}

      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition $ECS_TASK_DEFINITION \
            --query taskDefinition \
            --output json \
            > task-definition.json

      - name: Render new task definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        id: render-task-definition
        with:
          task-definition: task-definition.json
          container-name: backend
          image: ${{ env.ECR_URI }}:${{ github.sha }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-definition.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true